// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: pkg/lmproxyproto/cmd.proto

package lmproxyproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Error   Status = 0
	Status_Success Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Error",
		1: "Success",
	}
	Status_value = map[string]int32{
		"Error":   0,
		"Success": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lmproxyproto_cmd_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_lmproxyproto_cmd_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_Unknown Role = 0
	Role_Master  Role = 1
	Role_Slave   Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "Unknown",
		1: "Master",
		2: "Slave",
	}
	Role_value = map[string]int32{
		"Unknown": 0,
		"Master":  1,
		"Slave":   2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lmproxyproto_cmd_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_pkg_lmproxyproto_cmd_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{1}
}

type ClusterState int32

const (
	ClusterState_WaitReady ClusterState = 0
	ClusterState_Ready     ClusterState = 1
	ClusterState_Migration ClusterState = 2
)

// Enum value maps for ClusterState.
var (
	ClusterState_name = map[int32]string{
		0: "WaitReady",
		1: "Ready",
		2: "Migration",
	}
	ClusterState_value = map[string]int32{
		"WaitReady": 0,
		"Ready":     1,
		"Migration": 2,
	}
)

func (x ClusterState) Enum() *ClusterState {
	p := new(ClusterState)
	*p = x
	return p
}

func (x ClusterState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lmproxyproto_cmd_proto_enumTypes[2].Descriptor()
}

func (ClusterState) Type() protoreflect.EnumType {
	return &file_pkg_lmproxyproto_cmd_proto_enumTypes[2]
}

func (x ClusterState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterState.Descriptor instead.
func (ClusterState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{2}
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID   int32  `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`    // 节点ID
	NodeAddr string `protobuf:"bytes,2,opt,name=nodeAddr,proto3" json:"nodeAddr,omitempty"` // 节点地址
	TcpAddr  string `protobuf:"bytes,3,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"`   // 节点tcp对外地址
	WsAddr   string `protobuf:"bytes,4,opt,name=wsAddr,proto3" json:"wsAddr,omitempty"`     // 节点websocket对外地址
	Weight   int32  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`    // 节点权重
	Role     Role   `protobuf:"varint,6,opt,name=role,proto3,enum=Role" json:"role,omitempty"`
	Join     bool   `protobuf:"varint,7,opt,name=join,proto3" json:"join,omitempty"` // 是否是新加入的节点
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodeID() int32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *Node) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

func (x *Node) GetTcpAddr() string {
	if x != nil {
		return x.TcpAddr
	}
	return ""
}

func (x *Node) GetWsAddr() string {
	if x != nil {
		return x.WsAddr
	}
	return ""
}

func (x *Node) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Node) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_Unknown
}

func (x *Node) GetJoin() bool {
	if x != nil {
		return x.Join
	}
	return false
}

type ConnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID int32 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"` // 节点ID
}

func (x *ConnectReq) Reset() {
	*x = ConnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReq) ProtoMessage() {}

func (x *ConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReq.ProtoReflect.Descriptor instead.
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectReq) GetNodeID() int32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

type ConnectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID    int32 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`       // 节点ID
	ClusterID int32 `protobuf:"varint,2,opt,name=clusterID,proto3" json:"clusterID,omitempty"` // 分布式ID
}

func (x *ConnectInfo) Reset() {
	*x = ConnectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInfo) ProtoMessage() {}

func (x *ConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInfo.ProtoReflect.Descriptor instead.
func (*ConnectInfo) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectInfo) GetNodeID() int32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *ConnectInfo) GetClusterID() int32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

type ClusterConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterID int32 `protobuf:"varint,3,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
}

func (x *ClusterConfigReq) Reset() {
	*x = ClusterConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigReq) ProtoMessage() {}

func (x *ClusterConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigReq.ProtoReflect.Descriptor instead.
func (*ClusterConfigReq) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterConfigReq) GetClusterID() int32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

type ClusterConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version         int32         `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                 // 配置版本
	SlotCount       int32         `protobuf:"varint,2,opt,name=slotCount,proto3" json:"slotCount,omitempty"`             // slot 总数量
	ClusterID       int32         `protobuf:"varint,3,opt,name=clusterID,proto3" json:"clusterID,omitempty"`             // cluster id
	Replica         int32         `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`                 // 副本数
	State           ClusterState  `protobuf:"varint,5,opt,name=state,proto3,enum=ClusterState" json:"state,omitempty"`   // 状态
	Slots           []byte        `protobuf:"bytes,6,opt,name=slots,proto3" json:"slots,omitempty"`                      // slot bitmap
	Nodes           []*Node       `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`                      // 节点信息
	LeaderID        int32         `protobuf:"varint,8,opt,name=leaderID,proto3" json:"leaderID,omitempty"`               // 领导节点的id
	ImportClusterID int32         `protobuf:"varint,9,opt,name=importClusterID,proto3" json:"importClusterID,omitempty"` // 要导入的分布式ID
	ImportWill      []byte        `protobuf:"bytes,10,opt,name=importWill,proto3" json:"importWill,omitempty"`           // 将要引入的slots
	ExportWill      []byte        `protobuf:"bytes,11,opt,name=exportWill,proto3" json:"exportWill,omitempty"`           // 将要导出的slots
	Exporting       []byte        `protobuf:"bytes,12,opt,name=exporting,proto3" json:"exporting,omitempty"`             // 正在导出的slot（正在导出的slot将被锁定，不接受数据）
	ExportedList    *ExportedList `protobuf:"bytes,13,opt,name=exportedList,proto3" json:"exportedList,omitempty"`       // 已导出的slot
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterConfig) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterConfig) GetSlotCount() int32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *ClusterConfig) GetClusterID() int32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

func (x *ClusterConfig) GetReplica() int32 {
	if x != nil {
		return x.Replica
	}
	return 0
}

func (x *ClusterConfig) GetState() ClusterState {
	if x != nil {
		return x.State
	}
	return ClusterState_WaitReady
}

func (x *ClusterConfig) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ClusterConfig) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterConfig) GetLeaderID() int32 {
	if x != nil {
		return x.LeaderID
	}
	return 0
}

func (x *ClusterConfig) GetImportClusterID() int32 {
	if x != nil {
		return x.ImportClusterID
	}
	return 0
}

func (x *ClusterConfig) GetImportWill() []byte {
	if x != nil {
		return x.ImportWill
	}
	return nil
}

func (x *ClusterConfig) GetExportWill() []byte {
	if x != nil {
		return x.ExportWill
	}
	return nil
}

func (x *ClusterConfig) GetExporting() []byte {
	if x != nil {
		return x.Exporting
	}
	return nil
}

func (x *ClusterConfig) GetExportedList() *ExportedList {
	if x != nil {
		return x.ExportedList
	}
	return nil
}

type ClusterConfigListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterConfigs []*ClusterConfig `protobuf:"bytes,1,rep,name=clusterConfigs,proto3" json:"clusterConfigs,omitempty"`
}

func (x *ClusterConfigListResp) Reset() {
	*x = ClusterConfigListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfigListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigListResp) ProtoMessage() {}

func (x *ClusterConfigListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigListResp.ProtoReflect.Descriptor instead.
func (*ClusterConfigListResp) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterConfigListResp) GetClusterConfigs() []*ClusterConfig {
	if x != nil {
		return x.ClusterConfigs
	}
	return nil
}

type Exported struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No    string `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Slots []byte `protobuf:"bytes,2,opt,name=slots,proto3" json:"slots,omitempty"` // 已导出的slots
	Path  string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`   // 对应的备份路径
}

func (x *Exported) Reset() {
	*x = Exported{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exported) ProtoMessage() {}

func (x *Exported) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exported.ProtoReflect.Descriptor instead.
func (*Exported) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{6}
}

func (x *Exported) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *Exported) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *Exported) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExportedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exported []*Exported `protobuf:"bytes,1,rep,name=exported,proto3" json:"exported,omitempty"`
}

func (x *ExportedList) Reset() {
	*x = ExportedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportedList) ProtoMessage() {}

func (x *ExportedList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportedList.ProtoReflect.Descriptor instead.
func (*ExportedList) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{7}
}

func (x *ExportedList) GetExported() []*Exported {
	if x != nil {
		return x.Exported
	}
	return nil
}

type Exporting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots []byte `protobuf:"bytes,1,opt,name=slots,proto3" json:"slots,omitempty"` // 导出中的slots
}

func (x *Exporting) Reset() {
	*x = Exporting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exporting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exporting) ProtoMessage() {}

func (x *Exporting) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exporting.ProtoReflect.Descriptor instead.
func (*Exporting) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{8}
}

func (x *Exporting) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

type Imported struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	No    string `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Slots []byte `protobuf:"bytes,2,opt,name=slots,proto3" json:"slots,omitempty"` // 已导入的slots
}

func (x *Imported) Reset() {
	*x = Imported{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Imported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imported) ProtoMessage() {}

func (x *Imported) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imported.ProtoReflect.Descriptor instead.
func (*Imported) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{9}
}

func (x *Imported) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *Imported) GetSlots() []byte {
	if x != nil {
		return x.Slots
	}
	return nil
}

type ClusterConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // 配置版本
}

func (x *ClusterConfigResp) Reset() {
	*x = ClusterConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigResp) ProtoMessage() {}

func (x *ClusterConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigResp.ProtoReflect.Descriptor instead.
func (*ClusterConfigResp) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterConfigResp) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ClusterConfigChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterID int32 `protobuf:"varint,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Version   int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ClusterConfigChange) Reset() {
	*x = ClusterConfigChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterConfigChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigChange) ProtoMessage() {}

func (x *ClusterConfigChange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigChange.ProtoReflect.Descriptor instead.
func (*ClusterConfigChange) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{11}
}

func (x *ClusterConfigChange) GetClusterID() int32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

func (x *ClusterConfigChange) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`           //配置版本
	ClusterID    int32 `protobuf:"varint,2,opt,name=clusterID,proto3" json:"clusterID,omitempty"`       // 分布式ID
	LeaderID     int32 `protobuf:"varint,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`         // 领导ID
	TotalVersion int32 `protobuf:"varint,4,opt,name=totalVersion,proto3" json:"totalVersion,omitempty"` // 所有分布式配置的总版本（集群内的所有clusterConfig的version累加的值）
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{12}
}

func (x *Ping) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Ping) GetClusterID() int32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

func (x *Ping) GetLeaderID() int32 {
	if x != nil {
		return x.LeaderID
	}
	return 0
}

func (x *Ping) GetTotalVersion() int32 {
	if x != nil {
		return x.TotalVersion
	}
	return 0
}

type RegisterNodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    Status `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"` // 状态 0.失败 1.成功
	Reason    string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`              // 原因
	ClusterID int32  `protobuf:"varint,3,opt,name=clusterID,proto3" json:"clusterID,omitempty"`       // 分布式ID
}

func (x *RegisterNodeResp) Reset() {
	*x = RegisterNodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResp) ProtoMessage() {}

func (x *RegisterNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResp.ProtoReflect.Descriptor instead.
func (*RegisterNodeResp) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterNodeResp) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Error
}

func (x *RegisterNodeResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterNodeResp) GetClusterID() int32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

type StatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"` // 状态 0.失败 1.成功
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`              // 原因
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lmproxyproto_cmd_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_pkg_lmproxyproto_cmd_proto_rawDescGZIP(), []int{14}
}

func (x *StatusResp) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Error
}

func (x *StatusResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_lmproxyproto_cmd_proto protoreflect.FileDescriptor

var file_pkg_lmproxyproto_cmd_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a,
	0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x63, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x63, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x73, 0x41, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x73, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x05, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6a, 0x6f,
	0x69, 0x6e, 0x22, 0x24, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x22, 0x43, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22, 0x30, 0x0a,
	0x10, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22,
	0xae, 0x03, 0x0a, 0x0d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x6c, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x12,
	0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x6c, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x31, 0x0a,
	0x0c, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x4f, 0x0a, 0x15, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x22, 0x44, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x22, 0x21,
	0x0a, 0x09, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74,
	0x73, 0x22, 0x30, 0x0a, 0x08, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6e, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x13, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x7e, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x69, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22, 0x45, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x2a, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x10, 0x01, 0x2a, 0x2a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x10,
	0x02, 0x2a, 0x37, 0x0a, 0x0c, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f,
	0x3b, 0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_lmproxyproto_cmd_proto_rawDescOnce sync.Once
	file_pkg_lmproxyproto_cmd_proto_rawDescData = file_pkg_lmproxyproto_cmd_proto_rawDesc
)

func file_pkg_lmproxyproto_cmd_proto_rawDescGZIP() []byte {
	file_pkg_lmproxyproto_cmd_proto_rawDescOnce.Do(func() {
		file_pkg_lmproxyproto_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_lmproxyproto_cmd_proto_rawDescData)
	})
	return file_pkg_lmproxyproto_cmd_proto_rawDescData
}

var file_pkg_lmproxyproto_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_lmproxyproto_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_lmproxyproto_cmd_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: Status
	(Role)(0),                     // 1: Role
	(ClusterState)(0),             // 2: ClusterState
	(*Node)(nil),                  // 3: Node
	(*ConnectReq)(nil),            // 4: ConnectReq
	(*ConnectInfo)(nil),           // 5: ConnectInfo
	(*ClusterConfigReq)(nil),      // 6: ClusterConfigReq
	(*ClusterConfig)(nil),         // 7: ClusterConfig
	(*ClusterConfigListResp)(nil), // 8: ClusterConfigListResp
	(*Exported)(nil),              // 9: Exported
	(*ExportedList)(nil),          // 10: ExportedList
	(*Exporting)(nil),             // 11: Exporting
	(*Imported)(nil),              // 12: Imported
	(*ClusterConfigResp)(nil),     // 13: ClusterConfigResp
	(*ClusterConfigChange)(nil),   // 14: ClusterConfigChange
	(*Ping)(nil),                  // 15: Ping
	(*RegisterNodeResp)(nil),      // 16: RegisterNodeResp
	(*StatusResp)(nil),            // 17: StatusResp
}
var file_pkg_lmproxyproto_cmd_proto_depIdxs = []int32{
	1,  // 0: Node.role:type_name -> Role
	2,  // 1: ClusterConfig.state:type_name -> ClusterState
	3,  // 2: ClusterConfig.nodes:type_name -> Node
	10, // 3: ClusterConfig.exportedList:type_name -> ExportedList
	7,  // 4: ClusterConfigListResp.clusterConfigs:type_name -> ClusterConfig
	9,  // 5: ExportedList.exported:type_name -> Exported
	0,  // 6: RegisterNodeResp.status:type_name -> Status
	0,  // 7: StatusResp.status:type_name -> Status
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_lmproxyproto_cmd_proto_init() }
func file_pkg_lmproxyproto_cmd_proto_init() {
	if File_pkg_lmproxyproto_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_lmproxyproto_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfigListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exported); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exporting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Imported); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterConfigChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_lmproxyproto_cmd_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_lmproxyproto_cmd_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lmproxyproto_cmd_proto_goTypes,
		DependencyIndexes: file_pkg_lmproxyproto_cmd_proto_depIdxs,
		EnumInfos:         file_pkg_lmproxyproto_cmd_proto_enumTypes,
		MessageInfos:      file_pkg_lmproxyproto_cmd_proto_msgTypes,
	}.Build()
	File_pkg_lmproxyproto_cmd_proto = out.File
	file_pkg_lmproxyproto_cmd_proto_rawDesc = nil
	file_pkg_lmproxyproto_cmd_proto_goTypes = nil
	file_pkg_lmproxyproto_cmd_proto_depIdxs = nil
}
